serveur Valpineta:{
    icon:https://icons.terrastruct.com/essentials%2F112-server.svg
}
Application Valpineta{
    label.near: top-left
}

Application Valpineta.Screen 
Application Valpineta.Stores.Attributs
Application Valpineta.Stores.Methodes

Application Valpineta.Screen.NouveauSignalementScreen -> Application Valpineta.Stores.Attributs: Ajout d'un signalement
Application Valpineta.Stores.Attributs -> Application Valpineta.Stores.Methodes : si l'utilisateur est connecté
Application Valpineta.Stores.Methodes -> serveur Valpineta : signalements envoyés
Application Valpineta.Stores.Methodes -> Application Valpineta.Stores.Methodes : "Chrone envoyant les signalements"
serveur Valpineta -> Application Valpineta.Stores.Methodes : réponse du serveur
Application Valpineta.Stores.Methodes -> Application Valpineta.Screen.NouveauSignalementScreen: Informer l'utilisateur