serveur Valpineta:{
    icon:https://icons.terrastruct.com/essentials%2F112-server.svg
}
Application Valpineta{
    label.near: top-left
}

Application Valpineta.Screen 
Application Valpineta.Stores.Attributs
Application Valpineta.Stores.Methodes

Application Valpineta.Screen -> Application Valpineta.Stores.Attributs: Ajout d'une donnée
Application Valpineta.Stores.Attributs -> Application Valpineta.Stores.Methodes : si l'utilisateur est connecté
Application Valpineta.Stores.Methodes -> serveur Valpineta : données envoyés
Application Valpineta.Stores.Methodes -> Application Valpineta.Stores.Methodes : "Chrone envoyant les données"
serveur Valpineta -> Application Valpineta.Stores.Methodes : réponse du serveur
Application Valpineta.Stores.Methodes -> Application Valpineta.Screen: Informer l'utilisateur