serveur Valpineta:{
    icon:https://icons.terrastruct.com/essentials%2F112-server.svg
}
Application Valpineta{
    label.near: top-left
}
Application Valpineta.Services
Application Valpineta.Stores
Application Valpineta.Screen 

Application Valpineta.Screen.NouveauSignalementScreen -> Application Valpineta.Stores.SynchroMontante: Ajout d'un signalement
Application Valpineta.Stores.SynchroMontante -> Application Valpineta.Services.SynchroMontanteServiceSignalement : si l'utilisateur est connecté
Application Valpineta.Services.SynchroMontanteServiceSignalement -> serveur Valpineta : signalements envoyés
serveur Valpineta -> Application Valpineta.Services.SynchroMontanteServiceSignalement : réponse du serveur
Application Valpineta.Services.SynchroMontanteServiceSignalement -> Application Valpineta.Screen.NouveauSignalementScreen: Informer l'utilisateur

Application Valpineta.Stores.SynchroMontante -> Application Valpineta.Screen.NouveauSignalementScreen : non connecté
(Application Valpineta.Stores.SynchroMontante -> Application Valpineta.Screen.NouveauSignalementScreen)[0].style.stroke:red

