serveur Valpineta: {
  icon: https://icons.terrastruct.com/essentials%2F112-server.svg
}
Application Valpineta
Application Valpineta.Services
Application Valpineta.Screen

Application Valpineta.Screen -> Application Valpineta.Services.SynchroDescendante: Intervale définit.

Application Valpineta.Services.SynchroDescendante <-> serveur Valpineta: Sous couvert de réseau
(Application Valpineta.Services.SynchroDescendante <-> serveur Valpineta)[0].style.stroke: red
